apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: integration-suite-test-component-image-source-yeip
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: integration-suite-test-component-image-source-yeip
    app.kubernetes.io/part-of: integration-suite-test-application-kwai
  name: integration-suite-test-component-image-source-yeip
  namespace: appstudio-e2e-test
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: integration-suite-test-component-image-source-yeip
    weight: 100
status: {}
